
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  'https://vdmsplcvhgzxjkgcrpwb.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbXNwbGN2aGd6eGprZ2NycHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODgxMTUsImV4cCI6MjA2MzA2NDExNX0.OWUut1woB4lTlebentLVXtBY7ErXigYjrAQkEEhSsP0',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
